name: lz4
category: others
channel: conda-forge
description: LZ4 Bindings for Python
license: BSD-3-Clause
homepage: https://github.com/python-lz4/python-lz4

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n lz4
    conda activate lz4
    ```
    
  - 安装软件包
    ```
    conda install lz4
    ```

upstream:
  backend: custom
  version_scheme: RPM
  version_url: http://www.oberhumer.com/opensource/lzo/download/
  regex: lzo-(\d+\.\d+).tar.gz