name: python
category: others
channel: conda-forge
description: General purpose programming language
license: Python-2.0
homepage: https://www.python.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n python
    conda activate python
    ```
    
  - 安装软件包
    ```
    conda install python
    ```