name: root
category: hpc
channel: conda-forge
description: ROOT is unified software for storing, processing, and analyzing scientific data used in particle physics.
license: LGPL-2.1-only
homepage: https://root.cern/

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n root
    conda activate root
    ```

  - 安装软件包
    ```
    conda install root
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: root-project/root
  version_prefix: v
  version_filter: rc
