name: bamtools
category: hpc
channel: bioconda
description: C++ API & command-line toolkit for working with BAM data
license: MIT
homepage: https://github.com/pezmaster31/bamtools

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bamtools
    conda activate bamtools
    ```
    
  - 安装软件包
    ```
    conda install bamtools
    ```

dependency-channels:
  - conda-forge
