name: mrtrix3
category: hpc
channel: bioconda
description: A set of tools to perform various advanced diffusion MRI analyses, including constrained spherical deconvolution (CSD), probabilistic tractography, track-density imaging, and apparent fibre density.
license: MPL-2.0
homepage: https://www.mrtrix.org

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n mrtrix3
    conda activate mrtrix3
    ```
    
  - 安装软件包
    ```
    conda install mrtrix3
    ```

dependency-channels:
  - conda-forge
