name: bioconductor-dnacopy
category: hpc
channel: bioconda
description: DNA Copy Number Data Analysis
license: GPL (>= 2)
homepage: https://bioconductor.org/packages/3.20/bioc/html/DNAcopy.html

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bioconductor-dnacopy
    conda activate bioconductor-dnacopy
    ```
    
  - 安装软件包
    ```
    conda install bioconductor-dnacopy
    ```

dependency-channels:
  - conda-forge
