name: geos
category: others
channel: conda-forge
description: Geometry Engine, Open Source
license: LGPL-2.1-only
homepage: https://libgeos.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n geos
    conda activate geos
    ```
    
  - 安装软件包
    ```
    conda install geos
    ```