name: gmp
category: others
channel: conda-forge
description: The GNU multiprecision library.
license: GPL-2.0-or-later OR LGPL-3.0-or-later
homepage: http://gmplib.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n gmp
    conda activate gmp
    ```
    
  - 安装软件包
    ```
    conda install gmp
    ```

upstream:
  backend: custom
  version_scheme: RPM
  version_url: https://gmplib.org/
  regex: GMP\s+(\d+\.\d+\.\d+)