name: trimal
category: hpc
channel: bioconda
description: A tool for the automated removal of spurious sequences or poorly aligned regions from a multiple sequence alignment.
license: GNU General Public License v3 or later (GPLv3+)
homepage: https://trimal.readthedocs.io

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n trimal
    conda activate trimal
    ```
    
  - 安装软件包
    ```
    conda install trimal
    ```

dependency-channels:
  - conda-forge