name: bioawk
category: hpc
channel: bioconda
description: BWK awk modified for biological data.
license: Free software license
homepage: https://github.com/lh3/bioawk

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bioawk
    conda activate bioawk
    ```
    
  - 安装软件包
    ```
    conda install bioawk
    ```

dependency-channels:
  - conda-forge