name: ffmpeg
category: others
channel: conda-forge
description: Cross-platform solution to record, convert and stream audio and video.
license: GPL-2.0-or-later
homepage: https://www.ffmpeg.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n ffmpeg
    conda activate ffmpeg
    ```
    
  - 安装软件包
    ```
    conda install ffmpeg
    ```