name: simpleitk
category: hpc
channel: conda-forge
description: Simplified interface to the Insight Toolkit for image registration and segmentation
license: Apache-2.0
homepage: http://www.simpleitk.org

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n simpleitk
    conda activate simpleitk
    ```
    
  - 安装软件包
    ```
    conda install simpleitk
    ```

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: SimpleITK/SimpleITK
  version_prefix: v
  version_filter: rc;b;latest