name: bioconductor-fastseg
category: hpc
channel: bioconda
description: fastseg - a fast segmentation algorithm
license: LGPL (>= 2.0)
homepage: https://bioconductor.org/packages/3.20/bioc/html/fastseg.html

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bioconductor-fastseg
    conda activate bioconductor-fastseg
    ```
    
  - 安装软件包
    ```
    conda install bioconductor-fastseg
    ```

dependency-channels:
  - conda-forge
