name: junit5
category: others
channel: conda-forge
description: The 5th major version of the programmer-friendly testing framework for Java and the JVM
license: EPL-2.0
homepage: https://github.com/junit-team/junit5

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n junit5
    conda activate junit5
    ```
    
  - 安装软件包
    ```
    conda install junit5
    ```