name: openblas
category: others
channel: conda-forge
description: An optimized BLAS library based on GotoBLAS2 1.13 BSD version
license: BSD-3-Clause
homepage: http://www.openblas.net/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n openblas
    conda activate openblas
    ```
    
  - 安装软件包
    ```
    conda install openblas
    ```