name: bcrypt
category: others
channel: conda-forge
description: Modern password hashing for your software and your servers
license: Apache-2.0
homepage: https://github.com/pyca/bcrypt/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bcrypt
    conda activate bcrypt
    ```
    
  - 安装软件包
    ```
    conda install bcrypt
    ```