name: swmm
category: others
channel: conda-forge
description: The EPA Storm Water Management Model (SWMM) is used throughout the world for planning, analysis, and design related to stormwater runoff, combined and sanitary sewers, and other drainage systems in urban areas.
license: CC0-1.0
homepage: https://www.epa.gov/water-research/storm-water-management-model-swmm

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n swmm
    conda activate swmm
    ```

  - 安装软件包
    ```
    conda install swmm
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: USEPA/Stormwater-Management-Model
  version_prefix: v
  version_filter: rc
