name: vue
category: others
channel: conda-forge
description: A progressive, incrementally-adoptable JavaScript framework for building UI on the web.
license: MIT
homepage: https://github.com/vuejs/vue

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n vue
    conda activate vue
    ```
    
  - 安装软件包
    ```
    conda install vue
    ```

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: vuejs/core
  version_prefix: v
  version_filter: HBase;rc;beta;alpha