name: libprotobuf
category: others
channel: conda-forge
description: Protocol Buffers - Google's data interchange format. C++ Libraries and protoc, the protobuf compiler.
license: BSD-3-Clause
homepage: https://developers.google.com/protocol-buffers/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n libprotobuf
    conda activate libprotobuf
    ```
    
  - 安装软件包
    ```
    conda install libprotobuf
    ```