name: typescript
category: others
channel: conda-forge
description: TypeScript is a superset of JavaScript that compiles to clean JavaScript output.
license: Apache-2.0
homepage: https://github.com/Microsoft/TypeScript

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n typescript
    conda activate typescript
    ```
    
  - 安装软件包
    ```
    conda install typescript
    ```

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: Microsoft/TypeScript
  version_prefix: v
  version_filter: beta;rc;