name: libxml2
category: others
channel: conda-forge
description: The XML C parser and toolkit of Gnome
license: MIT
homepage: http://xmlsoft.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n libxml2
    conda activate libxml2
    ```
    
  - 安装软件包
    ```
    conda install libxml2
    ```