name: cutadapt
category: hpc
channel: bioconda
description: Trim adapters from high-throughput sequencing reads.
license: MIT
homepage: https://cutadapt.readthedocs.io/

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n cutadapt
    conda activate cutadapt
    ```
    
  - 安装软件包
    ```
    conda install cutadapt
    ```

dependency-channels:
  - conda-forge
