name: libevent
category: others
channel: conda-forge
description: An event notification library.
license: BSD-3-Clause
homepage: http://libevent.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n libevent
    conda activate libevent
    ```
    
  - 安装软件包
    ```
    conda install libevent
    ```