name: mne
category: hpc
channel: conda-forge
description: MNE-Python is a software for MEG and EEG data analysis.
license: BSD-3-Clause
homepage: http://mne.tools

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n mne
    conda activate mne
    ```
    
  - 安装软件包
    ```
    conda install mne
    ```
