name: fasta
category: hpc
channel: conda-forge
description: The fasta Python package enables you to deal with biological sequence files easily.
license: MIT
homepage: https://github.com/xapple/fasta

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n fasta
    conda activate fasta
    ```

  - 安装软件包
    ```
    conda install fasta
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: xapple/fasta
  version_filter: rc
