name: libgrpc
category: others
channel: conda-forge
description: gRPC - A high-performance, open-source universal RPC framework
license: Apache-2.0
homepage: https://grpc.io/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n libgrpc
    conda activate libgrpc
    ```
    
  - 安装软件包
    ```
    conda install libgrpc
    ```