name: sqlite
category: database
channel: conda-forge
description: Implements a self-contained, zero-configuration, SQL database engine.
license: Public Domain
homepage: http://www.sqlite.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n sqlite
    conda activate sqlite
    ```
    
  - 安装软件包
    ```
    conda install sqlite
    ```

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: sqlite/sqlite
  version_prefix: version-
  version_filter: major;release;version