name: repeatmodeler
category: hpc
channel: bioconda
description: RepeatModeler is a de-novo repeat family identification and modeling package.
license: Open Software License v2.1
homepage: https://www.repeatmasker.org/RepeatModeler

usage: |

  - 添加Channel(可选)
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n repeatmodeler
    conda activate repeatmodeler
    ```
    
  - 安装软件包
    ```
    conda install repeatmodeler
    ```

dependency-channels:
  - conda-forge