name: lumpy-sv
category: hpc
channel: bioconda
description: a general probabilistic framework for structural variant discovery
license: MIT
homepage: https://github.com/arq5x/lumpy-sv

usage: |

  - 添加Channel(可选)
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n lumpy-sv
    conda activate lumpy-sv
    ```
    
  - 安装软件包
    ```
    conda install lumpy-sv
    ```

dependency-channels:
  - conda-forge