name: bioconductor-methylkit
category: hpc
channel: bioconda
description: DNA methylation analysis from high-throughput bisulfite sequencing results.
license: Artistic-2.0
homepage: https://bioconductor.org/packages/3.20/bioc/html/methylKit.html
maintainer: baigj
maintainer_email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bioconductor-methylkit
    conda activate bioconductor-methylkit
    ```
    
  - 安装软件包
    ```
    conda install bioconductor-methylkit
    ```

dependency-channels:
  - conda-forge
