name: flatbuffers
category: others
channel: conda-forge
description: Memory Efficient Serialization Library
license: Apache-2.0
homepage: http://google.github.io/flatbuffers/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n flatbuffers
    conda activate flatbuffers
    ```
    
  - 安装软件包
    ```
    conda install flatbuffers
    ```

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: google/flatbuffers
  version_prefix: v