name: maven
category: others
channel: conda-forge
description: A software project management and comprehension tool.
license: Apache-2.0
homepage: https://maven.apache.org

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n maven
    conda activate maven
    ```
    
  - 安装软件包
    ```
    conda install maven
    ```