name: mpc
category: others
channel: conda-forge
description: A C library for the arithmetic of complex numbers with arbitrarily high precision.
license: LGPL-3.0-or-later
homepage: http://www.multiprecision.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n mpc
    conda activate mpc
    ```
    
  - 安装软件包
    ```
    conda install mpc
    ```