name: ncview
category: hpc
channel: conda-forge
description: Ncview is a visual browser for netCDF format files.
license: GPL-3.0-only
homepage: http://meteora.ucsd.edu/~pierce/ncview_home_page.html

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n ncview
    conda activate ncview
    ```

  - 安装软件包
    ```
    conda install ncview
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: custom
  version_url: https://mirrors.mit.edu/macports/distfiles/ncview/
