name: gnuplot
category: hpc
channel: conda-forge
description: Gnuplot, plotting from command line
license: Gnuplot
homepage: https://github.com/gnuplot/gnuplot

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n gnuplot
    conda activate gnuplot
    ```
    
  - 安装软件包
    ```
    conda install gnuplot
    ```