name: psutil
category: others
channel: conda-forge
description: A cross-platform process and system utilities module for Python
license: BSD-3-Clause
homepage: https://github.com/giampaolo/psutil

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n psutil
    conda activate psutil
    ```
    
  - 安装软件包
    ```
    conda install psutil
    ```