name: mpb
category: hpc
channel: conda-forge
description: MIT Photonic-Bands - computation of photonic band structures in periodic media.
license: GPL-2.0-or-later
homepage: https://github.com/NanoComp/mpb

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n mpb
    conda activate mpb
    ```

  - 安装软件包
    ```
    conda install mpb
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: NanoComp/mpb
  version_prefix: v
  version_filter: rc
