name: muscle 
category: hpc
channel: bioconda
description: Multiple sequence and structure alignment with top benchmark scores scalable to thousands of sequences
license: GPL-3.0-only
homepage: https://github.com/rcedgar/muscle

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n muscle 
    conda activate muscle 
    ```
    
  - 安装软件包
    ```
    conda install muscle 
    ```

dependency-channels:
  - conda-forge
