name: hnswlib
category: others
channel: conda-forge
description: Python bindings for Hnswlib, a fast approximate nearest neighbor search package.
license: Apache-2.0
homepage: https://github.com/nmslib/hnswlib

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n hnswlib
    conda activate hnswlib
    ```

  - 安装软件包
    ```
    conda install hnswlib
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: nmslib/hnswlib
  version_prefix: v
  version_filter: rc
