name: snappy
category: others
channel: conda-forge
description: A fast compressor/decompressor
license: BSD-3-Clause
homepage: https://github.com/google/snappy

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n snappy
    conda activate snappy
    ```
    
  - 安装软件包
    ```
    conda install snappy
    ```