name: bayestyper
category: hpc
channel: bioconda
description: A method for variant graph genotyping based on exact alignment of k-mers
license: MIT
homepage: https://github.com/bioinformatics-centre/BayesTyper

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bayestyper
    conda activate bayestyper
    ```
    
  - 安装软件包
    ```
    conda install bayestyper
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: bioinformatics-centre/BayesTyper
  version_prefix: v