name: lastz
category: hpc
channel: bioconda
description: LASTZ is a program for aligning DNA sequences, a pairwise aligner.
license: MIT
homepage: http://www.bx.psu.edu/~rsharris/lastz/

usage: |

  - 添加Channel(可选)
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n lastz
    conda activate lastz
    ```
    
  - 安装软件包
    ```
    conda install lastz
    ```

dependency-channels:
  - conda-forge