name: bioconductor-batchelor
category: hpc
channel: bioconda
description: Single-Cell Batch Correction Methods
license: GPL-3
homepage: https://bioconductor.org/packages/3.20/bioc/html/batchelor.html

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bioconductor-batchelor
    conda activate bioconductor-batchelor
    ```
    
  - 安装软件包
    ```
    conda install bioconductor-batchelor
    ```

dependency-channels:
  - conda-forge
