name: expat
category: others
channel: conda-forge
description: Expat XML parser library in C
license: MIT
homepage: http://expat.sourceforge.net/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n expat
    conda activate expat
    ```
    
  - 安装软件包
    ```
    conda install expat
    ```