name: hmmer
category: hpc
channel: bioconda
description: Biosequence analysis using profile hidden Markov models.
license: BSD
homepage: http://hmmer.org/

usage: |

  - 添加Channel(可选)
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n hmmer
    conda activate hmmer
    ```
    
  - 安装软件包
    ```
    conda install hmmer
    ```

dependency-channels:
  - conda-forge
