name: hmmer
category: hpc
channel: bioconda
description: Biosequence analysis using profile hidden Markov models.
license: BSD
homepage: http://hmmer.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n hmmer
    conda activate hmmer
    ```
    
  - 安装软件包
    ```
    conda install hmmer
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: custom
  version_scheme: RPM
  version_url: http://hmmer.org/download.html
  regex: hmmer-(\d+\.\d+(?:\.\d+)?).tar.gz