name: rmats
category: hpc
channel: bioconda
description: MATS is a computational tool to detect differential alternative splicing events from RNA-Seq data.
license: Free for non-commercial use, see LICENSE file
homepage: http://rnaseq-mats.sourceforge.net

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n rmats
    conda activate rmats
    ```
    
  - 安装软件包
    ```
    conda install rmats
    ```

dependency-channels:
  - conda-forge
