name: lua
category: others
channel: conda-forge
description: Lua is a powerful, fast, lightweight, embeddable scripting language
license: MIT
homepage: http://www.lua.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n lua
    conda activate lua
    ```
    
  - 安装软件包
    ```
    conda install lua
    ```

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: lua/lua
  version_prefix: v
  version_filter: beta;alpha;w