name: bioconductor-maigespack
category: hpc
channel: bioconda
description: Functions to handle cDNA microarray data, including several methods of data analysis
license: GPL (>= 2)
homepage: https://bioconductor.org/packages/3.17/bioc/html/maigesPack.html

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bioconductor-maigespack
    conda activate bioconductor-maigespack
    ```
    
  - 安装软件包
    ```
    conda install bioconductor-maigespack
    ```

dependency-channels:
  - conda-forge
