name: salmon
category: hpc
channel: bioconda
description: Highly-accurate & wicked fast transcript-level quantification from RNA-seq reads using selective alignment.
license: GPLv3
homepage: https://github.com/COMBINE-lab/salmon

usage: |

  - 添加Channel(可选)
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n salmon
    conda activate salmon
    ```
    
  - 安装软件包
    ```
    conda install salmon
    ```

dependency-channels:
  - conda-forge
