name: bwa
category: hpc
channel: bioconda
description: The BWA read mapper.
license: GPL3
homepage: https://github.com/lh3/bwa

maintainer: baigj
maintainer_email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bwa
    conda activate bwa
    ```
    
  - 安装软件包
    ```
    conda install bwa
    ```

dependency-channels:
  - conda-forge