name: gradle
category: others
channel: conda-forge
description: Gradle - an open-source build-automation system
license: Apache-2.0
homepage: https://gradle.org

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n gradle
    conda activate gradle
    ```
    
  - 安装软件包
    ```
    conda install gradle
    ```