name: yambo
category: hpc
channel: conda-forge
description: Open-source many-body perturbation theory and time-dependent density functional theory
license: GPL-2.0-or-later
homepage: http://www.yambo-code.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n yambo
    conda activate yambo
    ```
    
  - 安装软件包
    ```
    conda install yambo
    ```