name: benchmark
category: others
channel: conda-forge
description: A microbenchmark support library
license: Apache-2.0
homepage: https://github.com/google/benchmark

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n benchmark
    conda activate benchmark
    ```
    
  - 安装软件包
    ```
    conda install benchmark
    ```