name: erlang
category: others
channel: conda-forge
description: A programming language used to build massively scalable soft real-time systems with requirements on high availability.
license: Apache-2.0
homepage: https://www.erlang.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n erlang
    conda activate erlang
    ```
    
  - 安装软件包
    ```
    conda install erlang
    ```