name: clipkit
category: hpc
channel: bioconda
description: Alignment trimming software for phylogenetics.
license: MIT
homepage: https://github.com/jlsteenwyk/clipkit

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n clipkit
    conda activate clipkit
    ```
    
  - 安装软件包
    ```
    conda install clipkit
    ```

dependency-channels:
  - conda-forge