name: centrifuge
category: hpc
channel: bioconda
description: Classifier for metagenomic sequences. Supports classifier scripts
license: GPL-3.0-only
homepage: https://github.com/DaehwanKimLab/centrifuge

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n centrifuge
    conda activate centrifuge
    ```
    
  - 安装软件包
    ```
    conda install centrifuge
    ```

dependency-channels:
  - conda-forge
