name: faiss
category: others
channel: conda-forge
description: A library for efficient similarity search and clustering of dense vectors.
license: MIT
homepage: https://faiss.ai/

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n faiss
    conda activate faiss
    ```

  - 安装软件包
    ```
    conda install faiss
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: facebookresearch/faiss
  version_prefix: v
  version_filter: rc
