name: scikit-learn
category: others
channel: conda-forge
description: A set of python modules for machine learning and data mining
license: BSD-3-Clause
homepage: http://scikit-learn.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n scikit-learn
    conda activate scikit-learn
    ```
    
  - 安装软件包
    ```
    conda install scikit-learn
    ```