name: lancedb
category: others
channel: conda-forge
description: Developer-friendly, serverless vector database for AI applications.
license: Apache-2.0
homepage: https://github.com/lancedb/lancedb

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n lancedb
    conda activate lancedb
    ```

  - 安装软件包
    ```
    conda install lancedb
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: lancedb/lancedb
  version_prefix: v
  version_filter: rc
