name: metis
category: others
channel: conda-forge
description: METIS is a set of serial programs for partitioning graphs, partitioning finite element meshes, and producing fill reducing orderings for sparse matrices. The algorithms implemented in METIS are based on the multilevel recursive-bisection, multilevel k-way, and multi-constraint partitioning schemes.
license: Apache-2.0
homepage: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n metis
    conda activate metis
    ```

  - 安装软件包
    ```
    conda install metis
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: KarypisLab/METIS
  version_prefix: v
  version_filter: rc;DistDGL
