name: rdma-core
category: hpc
channel: conda-forge
description: RDMA Core Userspace Libraries and Daemons
license: Linux-OpenIB
homepage: https://github.com/linux-rdma/rdma-core

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n rdma-core
    conda activate rdma-core
    ```
    
  - 安装软件包
    ```
    conda install rdma-core
    ```