name: relion
category: hpc
channel: bioconda
description: Image-processing software for cryo-electron microscopy.
license: GPL-2.0-or-later
homepage: https://github.com/3dem/relion

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n relion
    conda activate relion
    ```
    
  - 安装软件包
    ```
    conda install relion
    ```

dependency-channels:
  - conda-forge
