name: libopus
category: others
channel: conda-forge
description: Opus Interactive Audio Codec
license: BSD-3-Clause
homepage: http://opus-codec.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n libopus
    conda activate libopus
    ```
    
  - 安装软件包
    ```
    conda install libopus
    ```