name: libconfig
category: others
channel: conda-forge
description: C/C++ Configuration File Library
license: LGPL-2.1-only
homepage: http://hyperrealm.com/libconfig/libconfig.html

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n libconfig
    conda activate libconfig
    ```
    
  - 安装软件包
    ```
    conda install libconfig
    ```