name: pigz
category: others
channel: conda-forge
description: Parallel implementation of gzip
license: Zlib
homepage: https://zlib.net/pigz/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n pigz
    conda activate pigz
    ```
    
  - 安装软件包
    ```
    conda install pigz
    ```