name: gtest
category: others
channel: conda-forge
description: Google's C++ test framework
license: BSD-3-Clause
homepage: https://github.com/google/googletest

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n gtest
    conda activate gtest
    ```
    
  - 安装软件包
    ```
    conda install gtest
    ```