name: hisat2
category: hpc
channel: bioconda
description: Graph-based alignment of next generation sequencing reads to a population of genomes.
license: GPL-3.0-only
homepage: http://daehwankimlab.github.io/hisat2

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n hisat2
    conda activate hisat2
    ```

  - 安装软件包
    ```
    conda install hisat2
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: DaehwanKimLab/hisat2
  version_prefix: v
  version_filter: rc
