name: gzip
category: others
channel: conda-forge
description: The GNU zip complession utility
license: GPL-3.0-or-later
homepage: https://www.gnu.org/software/gzip/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n gzip
    conda activate gzip
    ```
    
  - 安装软件包
    ```
    conda install gzip
    ```

upstream:
  backend: custom
  version_scheme: RPM
  version_url: https://mirrors.nju.edu.cn/gnu/gzip/
  regex: gzip-(\d+\.\d+(?:\.\d+)?).tar.gz
