name: mopac
category: hpc
channel: conda-forge
description: The modern open-source version of the Molecular Orbital PACkage (MOPAC)
license: Apache-2.0
homepage: http://openmopac.net

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |
  
  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n mopac
    conda activate mopac
    ```
    
  - 安装软件包
    ```
    conda install mopac
    ```