name: figtree
category: hpc
channel: bioconda
description: FigTree is designed as a graphical viewer of phylogenetic trees and as a program for producing publication-ready figures.
license: GPLv2
homepage: https://github.com/rambaut/figtree

maintainer: baigj
maintainer_email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n figtree
    conda activate figtree
    ```
    
  - 安装软件包
    ```
    conda install figtree
    ```

dependency-channels:
  - conda-forge
