name: bioconductor-biovizbase
category: hpc
channel: bioconda
description: Basic graphic utilities for visualization of genomic data.
license: Artistic-2.0
homepage: https://bioconductor.org/packages/3.20/bioc/html/biovizBase.html
maintainer: baigj
maintainer_email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n bioconductor-biovizbase
    conda activate bioconductor-biovizbase
    ```
    
  - 安装软件包
    ```
    conda install bioconductor-biovizbase
    ```

dependency-channels:
  - conda-forge
