name: samblaster
category: hpc
channel: bioconda
description: Mark duplicates in and extract discordant and split reads from SAM files.
license: MIT
homepage: https://github.com/GregoryFaust/samblaster

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels bioconda
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n samblaster
    conda activate samblaster
    ```
    
  - 安装软件包
    ```
    conda install samblaster
    ```

dependency-channels:
  - conda-forge