name: numpy
category: others
channel: conda-forge
description: The fundamental package for scientific computing with Python.
license: BSD-3-Clause
homepage: http://numpy.org/

maintainer: baigj
maintainer-email: guangjiebai@gmail.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n numpy
    conda activate numpy
    ```
    
  - 安装软件包
    ```
    conda install numpy
    ```

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: numpy/numpy
  version_prefix: v
  version_filter: rc;b;dev