name: openbabel
category: hpc
channel: conda-forge
description: A chemical toolbox designed to speak the many languages of chemical data.
license: GPL-2.0-only
homepage: http://openbabel.org/

maintainer: zhangxinyuehfad
maintainer-email: starmoon_zhang@163.com

usage: |

  - 添加Channel
    ```
    conda config --add channels conda-forge
    ```

  - 创建隔离环境(可选)
    ```
    conda create -n openbabel
    conda activate openbabel
    ```

  - 安装软件包
    ```
    conda install openbabel
    ```

dependency-channels:
  - conda-forge

upstream:
  backend: GitHub
  version_scheme: RPM
  version_url: openbabel/openbabel
  version_prefix: openbabel-
  version_filter: rc
